--- 
commit:
  scope: true
  refs: true
  co_authoring: true
  description: true
  refs_types: ["Refs", "Fixes", "Closes"]
  refs_text: "<your-team>-"
  min_message_length: 5
  max_message_length: 100
  max_description_length: 5
  scope_length: 15
  co_authoring_file: co-authors.yml
  types:
    - name: feat
      description: A new feature
    - name: fix 
      description: A bug fix
    - name: style
      description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - name: test 
      description: Adding missing tests or correcting existing tests
    - name: refactor
      description:  A code change that neither fixes a bug nor adds a feature
    - name: build
      description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"
    - name: ci
      description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"
    - name: chore 
      description: Other changes that don't modify src or test files
    - name: revert
      description: Reverts a previous commit
    - name: docs
      description: Documentation only changes
message:
    select_files: "Select files to commit:"
    staged_files: "Selected files to commit:"
    change_type: "Select change type:"
    scope: "What is the scope of this change? (enter to skip)"
    commit_message: "Enter a commit message: (max %d chars)"
    description_message: "Enter extra details - %s lines remaining (enter to finish):"
    refs_num: "Enter a reference to your ticket %s (enter to skip):"
    refs_type: "What is the type of reference?"
    co_author_yes_no: "Would you like to add a co-author"
    co_author: "Who is your co-author?"
    co_author_name: "What is your co-author's name?"
    co_author_email: "What is your co-author's email address?"
exit:
    not_a_repo: Current directory is not in a repository - exiting script
    no_files_selected: No files selected for staging area - exiting script
    no_files_to_commit: No modified files, nothing to commit - exiting script
    commit_error: "Unexpected error while trying to perform: \n  %s"
    push_error: Could not push to remote, check your permissions - exiting script
    push_successful: Successfully pushed to remote.
